#ifndef VARIABLESGLOBALES_H_INCLUDED
#define VARIABLESGLOBALES_H_INCLUDED

#define ANIO_PREDETERMINADO 2004
#define MES_PREDETERMINADO 8
#define DIA_PREDETERMINADO 6
#define DIA_MAXIMO 31
#define DIA_CASI_MAXIMO 30
#define FEBRERO_NORMAL 28
#define FEBRERO_BISIESTO 29
#define CASO1 100
#define CASO2 400
#define MAX_MESES 12
#define J_0 0
#define J_4 4

enum {ENERO=1, FEBRERO, MARZO, ABRIL, MAYO, JUNIO, JULIO
, AGOSTO, SEPTIEMBRE, OCTUBRE, NOVIEMBRE, DICIEMBRE};


#endif // VARIABLESGLOBALES_H_INCLUDED
